name: twitter scraper deploy

on:
  push:
    paths:
      - .github/workflows/twitter-scraper-deploy.yaml
      - scraper/twitter/**
    branches:
      - main
      - add-cron-action-for-twitter-scraper

jobs:
    build:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: scraper/twitter
      steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          make install-deps

      - name: Run unit tests
        run: |
          make test

      - name: Setup env variables
# multistring env variables check this out
# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#multiline-strings
#

        run: |
          echo 'SCP_FILES=scraper/twitter/build.tar' >> $GITHUB_ENV
          echo 'ARCHIVE=build.tar' >> $GITHUB_ENV

          echo 'SCP_TARGET<<EOF' >> $GITHUB_ENV
          cat ./deploy/target.txt >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

          tar -cvf build.tar $(cat deploy/files.txt)

      - name: Copy file via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_DEPLOY_USERNAME }}
          key: ${{ secrets.DROPLET_DEPLOY_SSHKEY }}
          source: ${{ env.SCP_FILES }}
          target: ${{ env.SCP_TARGET }}
          overwrite: true
      - name: Executing remote  command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_DEPLOY_USERNAME }}
          key: ${{ secrets.DROPLET_DEPLOY_SSHKEY }}
          script: cd ${{ env.SCP_TARGET }}/scraper/twitter && tar -xvf ${{ env.ARCHIVE }} && rm -rf ${{ env.ARCHIVE }}
